package com.grpc;

import com.google.protobuf.ByteString;
import com.grpc.Config.HelloReply;
import com.grpc.Config.HelloRequest;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;

public class GrpcClient extends Thread {

    public static void main(String[] args) {

        GrpcClient t1 = new GrpcClient();
        GrpcClient t2 = new GrpcClient();
        GrpcClient t3 = new GrpcClient();
        GrpcClient t4 = new GrpcClient();
        GrpcClient t5 = new GrpcClient();
        GrpcClient t6 = new GrpcClient();
        GrpcClient t7 = new GrpcClient();
        GrpcClient t8 = new GrpcClient();
        GrpcClient t9 = new GrpcClient();
        GrpcClient t10 = new GrpcClient();
        GrpcClient t11 = new GrpcClient();
        GrpcClient t12 = new GrpcClient();
        GrpcClient t13 = new GrpcClient();
        GrpcClient t14 = new GrpcClient();
        GrpcClient t15 = new GrpcClient();
        GrpcClient t16 = new GrpcClient();
        GrpcClient t17 = new GrpcClient();
        GrpcClient t18 = new GrpcClient();
        GrpcClient t19 = new GrpcClient();
        GrpcClient t20 = new GrpcClient();
        GrpcClient t21 = new GrpcClient();
        GrpcClient t22 = new GrpcClient();
        GrpcClient t23 = new GrpcClient();
        GrpcClient t24 = new GrpcClient();
        GrpcClient t25 = new GrpcClient();
        GrpcClient t26 = new GrpcClient();
        GrpcClient t27 = new GrpcClient();
        GrpcClient t28 = new GrpcClient();
        GrpcClient t29 = new GrpcClient();
        GrpcClient t30 = new GrpcClient();
        GrpcClient t31 = new GrpcClient();
        GrpcClient t32 = new GrpcClient();
        GrpcClient t33 = new GrpcClient();
        GrpcClient t34 = new GrpcClient();
        GrpcClient t35 = new GrpcClient();
        GrpcClient t36 = new GrpcClient();
        GrpcClient t37 = new GrpcClient();
        GrpcClient t38 = new GrpcClient();
        GrpcClient t39 = new GrpcClient();
        GrpcClient t40 = new GrpcClient();
        GrpcClient t41 = new GrpcClient();
        GrpcClient t42 = new GrpcClient();
        GrpcClient t43 = new GrpcClient();
        GrpcClient t44 = new GrpcClient();
        GrpcClient t45 = new GrpcClient();
        GrpcClient t46 = new GrpcClient();
        GrpcClient t47 = new GrpcClient();
        GrpcClient t48 = new GrpcClient();
        GrpcClient t49 = new GrpcClient();
        GrpcClient t50 = new GrpcClient();
        GrpcClient t51 = new GrpcClient();
        GrpcClient t52 = new GrpcClient();
        GrpcClient t53 = new GrpcClient();
        GrpcClient t54 = new GrpcClient();
        GrpcClient t55 = new GrpcClient();
        GrpcClient t56 = new GrpcClient();
        GrpcClient t57 = new GrpcClient();
        GrpcClient t58 = new GrpcClient();
        GrpcClient t59 = new GrpcClient();
        GrpcClient t60 = new GrpcClient();
        GrpcClient t61 = new GrpcClient();
        GrpcClient t62 = new GrpcClient();
        GrpcClient t63 = new GrpcClient();
        GrpcClient t64 = new GrpcClient();
        GrpcClient t65 = new GrpcClient();
        GrpcClient t66 = new GrpcClient();
        GrpcClient t67 = new GrpcClient();
        GrpcClient t68 = new GrpcClient();
        GrpcClient t69 = new GrpcClient();
        GrpcClient t70 = new GrpcClient();
        GrpcClient t71 = new GrpcClient();
        GrpcClient t72 = new GrpcClient();
        GrpcClient t73 = new GrpcClient();
        GrpcClient t74 = new GrpcClient();
        GrpcClient t75 = new GrpcClient();
        GrpcClient t76 = new GrpcClient();
        GrpcClient t77 = new GrpcClient();
        GrpcClient t78 = new GrpcClient();
        GrpcClient t79 = new GrpcClient();
        GrpcClient t80 = new GrpcClient();
        GrpcClient t81 = new GrpcClient();
        GrpcClient t82 = new GrpcClient();
        GrpcClient t83 = new GrpcClient();
        GrpcClient t84 = new GrpcClient();
        GrpcClient t85 = new GrpcClient();
        GrpcClient t86 = new GrpcClient();
        GrpcClient t87 = new GrpcClient();
        GrpcClient t88 = new GrpcClient();
        GrpcClient t89 = new GrpcClient();
        GrpcClient t90 = new GrpcClient();
        GrpcClient t91 = new GrpcClient();
        GrpcClient t92 = new GrpcClient();
        GrpcClient t93 = new GrpcClient();
        GrpcClient t94 = new GrpcClient();
        GrpcClient t95 = new GrpcClient();
        GrpcClient t96 = new GrpcClient();
        GrpcClient t97 = new GrpcClient();
        GrpcClient t98 = new GrpcClient();
        GrpcClient t99 = new GrpcClient();
        GrpcClient t100 = new GrpcClient();
        t1.start();
        t2.start();
        t3.start();
        t4.start();
        t5.start();
        t6.start();
        t7.start();
        t8.start();
        t9.start();
        t10.start();
        t11.start();
        t12.start();
        t13.start();
        t14.start();
        t15.start();
        t16.start();
        t17.start();
        t18.start();
        t19.start();
        t20.start();
        t21.start();
        t22.start();
        t23.start();
        t24.start();
        t25.start();
        t26.start();
        t27.start();
        t28.start();
        t29.start();
        t30.start();
        t31.start();
        t32.start();
        t33.start();
        t34.start();
        t35.start();
        t36.start();
        t37.start();
        t38.start();
        t39.start();
        t40.start();
        t41.start();
        t42.start();
        t43.start();
        t44.start();
        t45.start();
        t46.start();
        t47.start();
        t48.start();
        t49.start();
        t50.start();
        t51.start();
        t52.start();
        t53.start();
        t54.start();
        t55.start();
        t56.start();
        t57.start();
        t58.start();
        t59.start();
        t60.start();
        t61.start();
        t62.start();
        t63.start();
        t64.start();
        t65.start();
        t66.start();
        t67.start();
        t68.start();
        t69.start();
        t70.start();
        t71.start();
        t72.start();
        t73.start();
        t74.start();
        t75.start();
        t76.start();
        t77.start();
        t78.start();
        t79.start();
        t80.start();
        t81.start();
        t82.start();
        t83.start();
        t84.start();
        t85.start();
        t86.start();
        t87.start();
        t88.start();
        t89.start();
        t90.start();
        t91.start();
        t92.start();
        t93.start();
        t94.start();
        t95.start();
        t96.start();
        t97.start();
        t98.start();
        t99.start();
        t100.start();
    }
    @Override
    public void run() {
        try {
           // int msgSizeKB = 450000000; // 450 MB data ,java.lang.OutOfMemoryError: Java heap space
            int msgSizeKB =   50000000; //1 MB data,
            StringBuilder sb = new StringBuilder(msgSizeKB);
            for (; ; ) {
                ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 8083).usePlaintext().build();
                GreeterGrpc.GreeterBlockingStub bookStub = GreeterGrpc.newBlockingStub(channel);
                HelloReply reply = bookStub.sayHello(HelloRequest.newBuilder().setKeyData(ByteString.copyFromUtf8(sb.toString())).build());
                //sb = null;
                System.out.println("Response from GrpcServer=" + reply.getMessage());
                channel.shutdownNow();
            }
        } catch (Exception e) {
            System.out.println("Caught inside run().");
        }
    }
}