package(default_visibility = ["//visibility:public"])

java_library(
    name = "stub",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    deps = [
        "//core",
        "//context",
        "@com_google_code_findbugs_jsr305",
        "@com_google_guava",
    ],
)

