FROM ubuntu:22.04

# make sure apt-get works in unattended mode
ENV DEBIAN_FRONTEND=noninteractive

# install the OS-level prerequisites for building protobuf and running the gradle build
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends ca-certificates build-essential wget curl openjdk-8-jdk && \
    apt-get autoclean -y && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

