package(default_visibility = ["//visibility:public"])

java_library(
    name = "protobuf-nano",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    deps = [
        "//core",
        "@com_google_code_findbugs_jsr305",
        "@com_google_guava",
        "@com_google_protobuf_nano_protobuf_javanano",
    ],
)

