/*
 * Copyright 2020 The gRPC Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.grpc.xds.internal;

import com.google.api.expr.v1alpha1.Expr;
import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableMap;
import com.google.protobuf.Descriptors.Descriptor;
import io.envoyproxy.envoy.config.rbac.v2.Policy;
import io.envoyproxy.envoy.config.rbac.v2.RBAC;
import io.grpc.xds.InterpreterException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Cel Evaluation Engine is part of the authorization framework in gRPC.
 * Cel Evaluation Engine takes one or two Envoy RBAC policies as input
 * and uses CEL library to evaluate the condition field 
 * inside each RBAC policy based on the provided Envoy Attributes. 
 * Cel Evaluation Engine will generate an authorization decision which
 * could be ALLOW, DENY or UNKNOWN.
 * 
 * <p>Use as in:
 * 
 * <pre>
 *  CelEvaluationEngine engine = new CelEvaluationEngine(rbacPolicies);
 *  AuthorizationDecision result = engine.evaluate();
 * </pre>
 */
public class CelEvaluationEngine<ReqT, RespT> {
  private final List<RBAC.Action> action;
  private final List<ImmutableMap<String, Expr>> conditions;

  /**
   * Creates a Cel Evaluation Engine from a list of Envoy RBACs.
   * The constructor can take either one or two Envoy RBACs.
   * When it takes two RBACs, the order has to be a RBAC with DENY action
   * followed by a RBAC with ALLOW action.
   * @param rbacs input Envoy RBAC list.
   * @throws IllegalArgumentException if the user inputs an invalid RBAC list.
   */
  public CelEvaluationEngine(List<RBAC> rbacs) throws IllegalArgumentException {
    if (rbacs.size() < 1 || rbacs.size() > 2) {
      throw new IllegalArgumentException(
        "Invalid RBAC list size, must provide either one RBAC or two RBACs. ");
    } 
    if (rbacs.size() == 2 && (rbacs.get(0).getAction() != RBAC.Action.DENY 
        || rbacs.get(1).getAction() != RBAC.Action.ALLOW)) {
      throw new IllegalArgumentException( "Invalid RBAC list, " 
          + "must provide a RBAC with DENY action followed by a RBAC with ALLOW action. ");
    }
    this.action = new ArrayList<>();
    this.conditions = new ArrayList<>();
    for (int i = 0; i < rbacs.size(); i++) {
      RBAC rbac = rbacs.get(i);
      Map<String, Expr> conditions = new HashMap<>();
      for (Map.Entry<String, Policy> entry: rbac.getPolicies().entrySet()) {
        conditions.put(entry.getKey(), entry.getValue().getCondition());
      }
      this.action.add(Preconditions.checkNotNull(rbac.getAction()));
      this.conditions.add(Preconditions.checkNotNull(ImmutableMap.copyOf(conditions)));
    }
  }

  /**
   * The evaluate function performs the core authorization mechanism of Cel Evaluation Engine.
   * Determines whether a gRPC call is allowed, denied, or unable to decide.
   * @param args evaluate argument that is used to evaluate the RBAC conditions.
   * @return an AuthorizationDecision generated by Cel Evaluation Engine.
   * @throws InterpreterException if something goes wrong in CEL library.
   */
  public AuthorizationDecision evaluate(EvaluateArgs<ReqT, RespT> args) 
    throws InterpreterException {
    AuthorizationDecision.Decision authorizationDecision = null;
    String authorizationContext = "";
    // Go through each RBAC in the Envoy RBAC list.
    for (int i = 0; i < this.action.size(); i++) {
      // Go through each condition in the RBAC policy.
      for (Map.Entry<String, Expr> entry : this.conditions.get(i).entrySet()) {
        try {
          if (matches(entry.getValue(), args)) {
            if (this.action.get(i) == RBAC.Action.ALLOW) {
              authorizationDecision = AuthorizationDecision.Decision.ALLOW;
            } else {
              authorizationDecision = AuthorizationDecision.Decision.DENY;
            }
            authorizationContext = "Policy matched: " + entry.getKey();
            return new AuthorizationDecision(authorizationDecision, authorizationContext);
          }
        } catch (IllegalArgumentException e) {
          // The authorization decision is UNKNOWN if any Envoy Attributes are missing in args.
          authorizationDecision = AuthorizationDecision.Decision.UNKNOWN;
          authorizationContext = "Unable to determine. Error: " + e.toString();
          return new AuthorizationDecision(authorizationDecision, authorizationContext);
        }
      }
    }
    if (this.action.size() == 2) {
      // If there are 2 RBACs, the authorization decision is DENY by default.
      authorizationDecision = AuthorizationDecision.Decision.DENY;
    } else if (this.action.get(0) == RBAC.Action.ALLOW) {
      authorizationDecision = AuthorizationDecision.Decision.DENY;
    } else {
      authorizationDecision = AuthorizationDecision.Decision.ALLOW;
    }
    authorizationContext = "No policies matched. ";
    return new AuthorizationDecision(authorizationDecision, authorizationContext);
  }

  /** Evaluate if a condition matches the given Enovy Attributes using Cel library. */
  private boolean matches(Expr conditions, EvaluateArgs<ReqT, RespT> args) 
    throws InterpreterException, IllegalArgumentException {
    // Set up interpreter used in Cel library's eval function.
    List<Descriptor> descriptors = new ArrayList<>();
    RuntimeTypeProvider messageProvider = DescriptorMessageProvider.dynamicMessages(descriptors);
    Dispatcher dispatcher = DefaultDispatcher.create();
    Interpreter interpreter = new DefaultInterpreter(messageProvider, dispatcher);
    // Set up activation used in Cel library's eval function.
    ImmutableMap<String, Object> apiAttributes = extractFields(args);
    Activation activation = Activation.copyOf(apiAttributes);
    // Parse the generated result object to a boolean variable.
    Object result = interpreter.createInterpretable(conditions).eval(activation);
    if (result instanceof Boolean) {
      return Boolean.parseBoolean(result.toString());
    }
    return false;
  }

  /** Extract Envoy Attributes from EvaluateArgs. */
  private ImmutableMap<String, Object> extractFields(
      EvaluateArgs<ReqT, RespT> args) throws IllegalArgumentException {
    if (args == null) {
      throw new IllegalArgumentException("EvaluateArgs is not found. ");
    }
    // Add the extracted Envoy Attributes to the attributes map.
    Map<String, Object> attributes = new HashMap<>();
    attributes.put("requestUrlPath", args.getRequestUrlPath());
    attributes.put("requestHost", args.getRequestHost());
    attributes.put("requestMethod", args.getRequestMethod());
    attributes.put("requestHeaders", args.getRequestHeaders());
    attributes.put("sourceAddress", args.getSourceAddress());
    attributes.put("sourcePort", args.getSourcePort());
    attributes.put("destinationAddress", args.getDestinationAddress());
    attributes.put("destinationPort", args.getDestinationPort());
    attributes.put("connectionRequestedServerName", args.getConnectionRequestedServerName());
    attributes.put("connectionUriSanPeerCertificate", args.getConnectionUriSanPeerCertificate());
    return ImmutableMap.copyOf(attributes);
  }
}
