/*
 * Copyright 2016, Google Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *    * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *
 *    * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package io.grpc.protobuf.reflection;

import com.google.protobuf.Descriptors.FileDescriptor;

import io.grpc.AbstractServiceDescriptor;
import io.grpc.MethodDescriptor;
import io.grpc.ServiceDescriptor;

import java.util.Collection;

/**
 * Descriptor for a protobuf-backed service. This adds a method to retrieve the protobuf file
 * descriptor, but otherwise only wraps a {@link ServiceDescriptor} instance.
 */
public abstract class ProtoServiceDescriptor extends AbstractServiceDescriptor {
  private final ServiceDescriptor wrappedServiceDescriptor;

  public ProtoServiceDescriptor(String name, MethodDescriptor<?, ?>... methods) {
    wrappedServiceDescriptor = new ServiceDescriptor(name, methods);
  }

  public ProtoServiceDescriptor(String name, Collection<MethodDescriptor<?, ?>> methods) {
    wrappedServiceDescriptor = new ServiceDescriptor(name, methods);
  }

  /** Returns the name from the wrapped {@link ServiceDescriptor}. */
  @Override
  public String getName() {
    return wrappedServiceDescriptor.getName();
  }

  /** Returns the methods from the wrapped {@link ServiceDescriptor}. */
  @Override
  public Collection<MethodDescriptor<?, ?>> getMethods() {
    return wrappedServiceDescriptor.getMethods();
  }
  
  /**
   * Children of ProtoServiceDescriptor should override this method and return the service's
   * protobuf file descriptor. This is intended to be generated by the protobuf compiler.
   */
  public abstract FileDescriptor getFile();
}
