syntax = "proto3";

package google.cloud.autosharding.v1main;

import "google/api/field_behavior.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

option java_package = "com.google.cloud.autosharding.v1main";
option java_multiple_files = true;
option java_outer_classname = "DynamicShardingProto";

// An auto-sharding service that assigns keys in an application's keyspace to
// abstract "endpoints", and which uses load information from clients to update
// that assignment over time. Assignments and load reports are scoped to an
// abstract "slicing target."
//
// Concrete examples of the concepts in this protocol:
//
// Endpoints:
// * Application servers
// * Pods in a Kubernetes cluster
// * Regions in a multi-regional service
//
// Keys:
// * User ids
// * Tenant ids in a multi-tenant system
//
// Load:
// * Request count
// * CPU cost of processing requests
service DynamicShardingService {
  // Opens a stream over which clients report load and the server delivers
  // sharding assignments.
  //
  // A given client may use this stream just to receive assignments or also to
  // report load, and it may opt in or out of reporting load at any time. (An
  // implementation of the DynamicSharding service may impose restrictions on
  // which clients are allowed to report load, and it may respond to clients
  // improperly reporting load by ignoring their reports or terminating their
  // streams with an error.)
  //
  // The client should keep this stream open at all times and reopen the stream
  // after it closes, with backoff if the stream closed without delivering any
  // data.
  rpc WatchShardingAssignment(stream WatchShardingAssignmentRequest)
      returns (stream WatchShardingAssignmentResponse);
}

// In each instance of this message, the client MUST set exactly one field.
message WatchShardingAssignmentRequest {
  // Initial client-side configuration necessary to set up the stream. This
  // field MUST be set in the first message sent, and it MUST NOT be set in
  // subsequent messages.
  InitialClientConfig init = 1 [(google.api.field_behavior) = OPTIONAL];

  // An aggregated snapshot of load data collected by this client.
  //
  // The client MUST include all load data it has collected since the last
  // report in this report (irrespective of whether the last report was sent
  // on this or a prior physical stream), and it MUST NOT include that data in
  // any subsequent report.
  //
  // This field MUST NOT be set in the first message sent.
  LoadReport load_report = 2 [(google.api.field_behavior) = OPTIONAL];
}

// In each instance of this message, the server will set exactly one field.
message WatchShardingAssignmentResponse {
  // Configuration dictating how the client should aggregate and send load
  // reports.
  //
  // The client MUST wait to send load reports until it has received the first
  // version of this config from the server (on this physical stream).
  LoadReportingConfig config = 1;

  // A chunk of a logical assignment.
  //
  // The server delivers an assignment as a sequence of one or more
  // `AssignmentChunk` messages followed by a single `AssignmentMetadata`
  // message. Clients MUST wait for an `AssignmentMetadata` message and combine
  // the prior chunks to form a logical assignment before using it.
  AssignmentChunk chunk = 2;

  // Metadata associated with the most recent chunked assignment. Acts as a
  // trailer indicating that the server has finished delivering all chunks for
  // that assignment.
  AssignmentMetadata metadata = 3;
}

// Initial client-side configuration necessary to set up the stream.
message InitialClientConfig {
  // The slicing target to which this client's load reports and assignments
  // apply.
  //
  // If this target is unknown to the server, the server will terminate the
  // stream with a NOT_FOUND error.
  //
  // If this client does not have permission to connect to this target, the
  // server will terminate the stream with a PERMISSION_DENIED error.
  string target = 1 [(google.api.field_behavior) = REQUIRED];

  // A UUID generated by this client upon instantiation. The client MUST reuse
  // the same UUID across DynamicSharding stream reconnections. It is
  // permissible but not expected for the client to use the same UUID across
  // process restarts.
  string client_uuid = 2 [(google.api.field_behavior) = REQUIRED];

  // The latest assignment generation that this client has received. If set, the
  // server will only send newer assignments.
  int64 current_generation = 3 [(google.api.field_behavior) = OPTIONAL];
}

// Server-specified configuration dictating how the client should report load.
message LoadReportingConfig {
  // The maximum fraction of total load in a `Load` message that appears in a
  // single `RangeLoad` message, if the range is not a single-key range. When
  // aggregating load data into a load report, the client MUST honor the latest
  // received value of this field as of when it started aggregating. (See the
  // `RangeLoad` documentation for a description of how the client should
  // aggregate load data into load reports.)
  //
  // This field will always be in the range [0, 1].
  double load_quantum_frac = 1;

  // The maximum length of slice keys in load reports. When aggregating load
  // data into a load report, the client MUST honor the latest received value
  // of this field as of when it started aggregating. (See the `RangeLoad`
  // documentation for a description of how the client should aggregate load
  // data into load reports.)
  int32 max_load_balancing_resolution_bytes = 2;

  // The interval at which this client should send `LoadReport` messages. After
  // it sends a given load report to the server, the client MUST wait for
  // roughly the interval specified by the latest received value of this field
  // before it sends its next load report.
  google.protobuf.Duration load_reporting_interval = 3;

  // The lower bound on a load report's `start_time_inclusive`, relative to the
  // client's current time when it starts computing the load report. Clients
  // should discard load data before this threshold.
  google.protobuf.Duration load_report_start_threshold = 4;
}

// A load report consisting of per-metric load snapshots.
message LoadReport {
  // Snapshots of load in the keyspace associated with one or more metrics.
  //
  // A key in this map is a named load metric to which the load applies. This
  // metric MUST be a "cost" metric, i.e., one where the total load for a given
  // application key over a time interval is the sum of the individual load
  // values recorded for that key over the time interval, and where the number
  // of endpoints assigned a given application key does not affect the total
  // load for that key.
  map<string, Load> metric_load = 1 [(google.api.field_behavior) = REQUIRED];

  // The inclusive start timestamp of the time range to which this load report
  // applies.
  google.protobuf.Timestamp start_time_inclusive = 2
      [(google.api.field_behavior) = REQUIRED];

  // The exclusive end timestamp of the time range to which this load report
  // applies.
  //
  // This end time MUST be roughly equal to the client's current time, i.e.,
  // the client must send this load report to the server immediately after
  // computing it.
  //
  // To ensure good load-balancing behavior, the clock used to set these
  // timestamps MUST be synchronized to within ~one second of the clocks of
  // other clients and the DynamicSharding service. Implementations of the
  // DynamicSharding service should have some mechanism for informing client
  // owners when they detect significantly delayed client load reports (which
  // suggests an actionable issue related to either network delays or clock
  // skew).
  google.protobuf.Timestamp end_time_exclusive = 3
      [(google.api.field_behavior) = REQUIRED];
}

// A per-key-range load snapshot.
message Load {
  // An ordered set of per-key-range load. Each key range's exclusive end is
  // implicitly the start of the next range in the ordered set.
  //
  // Entries here MUST have lexicographically increasing start keys, and two
  // entries MUST NOT have the same start key.
  //
  // Start keys in these entries MUST be at most
  // `max_load_balancing_resolution_bytes` bytes (using the latest received
  // value as of when the client started aggregating this load report).
  //
  // Clients MUST aggregate observed load values for a given key during this
  // report's time interval into a single value for the key by summing the
  // values, and clients MUST aggregate per-key load values into a single load
  // value for a key range by summing the values.
  //
  // A single range MUST contain at most `load_quantum_frac` of the total
  // load across all ranges, unless it is a single-key range. (A range is a
  // single-key range if the next range's start key is the immediate
  // lexicographic successor of this range's start key in the space of
  // bytestrings of length `max_load_balancing_resolution_bytes`.)
  //
  // Subject to the above constraints, clients MUST aggregate this load data
  // into as few key ranges as possible.
  //
  // Clients under memory pressure may report "inexact" load according to a
  // strategy specified by the DynamicSharding service owner, e.g., by
  // sampling observed load data rather than retaining each data point.
  //
  // Implementation sketch for aggregating load into a load report: maintain a
  // hash map from key to total load observed since the last report. When it is
  // time to send a new report, truncate the keys to
  // `max_load_balancing_resolution_bytes`, then sort the load values
  // lexicographically by key. Walk the keyspace starting from the min key,
  // maintaining a current "open range" and its total load. If adding the
  // current key to the current open range would push its total load over
  // `load_quantum_frac`, then "close" the range and start a new open range.
  // Otherwise, add the current key to the current open range.
  repeated RangeLoad key_load = 1;
}

// Load associated with a key range (whose end is implicitly defined by the
// next range's start).
message RangeLoad {
  // The key range's start.
  bytes start_key_inclusive = 1;

  // The aggregate load associated with this key range observed by this client
  // during the time interval in this load report.
  double load = 2;
}

// Metadata associated with an assignment.
message AssignmentMetadata {
  // The assignment's unique and monotonically-increasing version number.
  int64 generation = 1;
}

// A portion of an assignment of slices to endpoints. The individual fields'
// documentation describes how to reassemble a set of chunks into a complete
// assignment.
message AssignmentChunk {
  // A chunk of the set of assignments for individual slices.
  //
  // Clients MUST reassemble the complete `slice_assignments` list by
  // concatenating the contents of this field across chunks (in any order).
  repeated SliceAssignment slice_assignments = 1;

  // A chunk of the list of all endpoints present in this assignment.
  //
  // Clients MUST reassemble the complete `endpoints` list by concatenating the
  // contents of this field across chunks, in chunk order.
  repeated EndpointState endpoints = 2;
}

// An endpoint and any associated metadata.
message EndpointState {
  // The endpoint's name.
  string endpoint = 1;
}

// The assignment for an individual slice.
message SliceAssignment {
  // The slice to which endpoints are assigned.
  Slice slice = 1;

  // The endpoints assigned to this slice.
  repeated PerSliceEndpointState endpoints = 2;
}

// A single slice, i.e., a continuous range of keys.
message Slice {
  // The slice's start. Will be at most 512 bytes.
  bytes start_key_inclusive = 1;

  // The slice's end. Will be at most 512 bytes. If this field is unset, this
  // slice contains the largest allowed key (the 512-byte string 0xFFFF...).
  bytes end_key_exclusive = 2;
}

// An endpoint assigned to a slice, along with any associated metadata about
// the endpoint in the context of that slice.
message PerSliceEndpointState {
  // An endpoint, specified as an index into the complete assignment's
  // reassembled `endpoints` list.
  int32 endpoint_index = 1;
}
