package io.grpc;

/**
 * TODO: Insert description here. (generated by notcarl)
 */
public final class CoreThread {
  private static final ThreadLocal<Boolean> inTransport = new ThreadLocal<Boolean>() {
    @Override
    protected Boolean initialValue() {
      return false;
    }
  };

  public static void enter() {
    inTransport.set(true);
  }

  public static void exit() {
    inTransport.remove();
  }

  public static void assertTransport() {
    if (!inTransport.get()) {
      throw new AssertionError("Expected to be in a transport thread");
    }
  }
}

