name: GitHub Actions Branch Testing

on:
  push:
    branches:
    - master
    - 'v1.*'
  schedule:
  - cron: '54 19 * * SUN' # weekly at a "random" time

permissions:
  contents: read

jobs:
  arm64:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        jre: [17]
      fail-fast: false # Should swap to true if we grow a large matrix

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jre }}
        distribution: 'temurin'

    - name: Gradle cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build
      run: ./gradlew -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs='-Xmx1g' -PskipAndroid=true -PskipCodegen=true -PerrorProne=false test

